backend:
  name: github
  repo: BobaBird/wellness-netlify

media_folder: static/assets

collections:
  - name: post
    label: Posts
    folder: src/posts
    create: true
    fields:
      - { name: title, label: title, required: false }
      - { name: date, label: times, widget: date, required: false }
      - { name: body, label: Post, widget: markdown }
      